app:
  name: "web_app"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_backups: 7
  max_age: 67
  max_open_conns: 10
  max_idle_conns: 10

mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "root123456"
  dbname: "sql_demo"

redis:
  host: "127.0.0.1"
  port: 16379
  db: 0